spring:
    datasource:
        url: jdbc:mysql://localhost:3306/red-envelope?serverTimezone=CST&useSSL=false
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
    rabbitmq:
        port: 5672
        host: 127.0.0.1
        username: root
        password: 123456
        virtual-host: /root
        listener:
            direct:
                consumers-per-queue: 10
                retry:
                    max-attempts: 2

            simple:
                concurrency: 8
                max-concurrency: 10
                retry:
                    max-attempts: 2
        template:
            mandatory: true
    redis:
        cluster:
            # 各 Redis 节点信息
            nodes: 127.0.0.1:7000,127.0.0.1:7100,127.0.0.1:7200

    jackson:
        serialization:
            indent_output: true

    mybatis:
        configuration:
            #    开启驼峰映射
            map-underscore-to-camel-case: true
        mapper-locations: classpath*:mapper/*.xml


server:
    tomcat:
        max-threads: 500
        min-spare-threads: 100
        accept-count: 400

