---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/9/8 20:05
---

redis.call("SET",KEYS[1],ARGV[1])
local current = redis.call('GET', KEYS[1])
return current
